---
apiVersion: v1
kind: Secret
metadata:
  name: lacework-api
type: Opaque
data:
  api-key: <BASE64_ENCODED_API_KEY>
  api-secret: <BASE64_ENCODED_API_SECRET>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacework-custom-report
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: lacework-custom-report
  template:
    metadata:
      labels:
        app: lacework-custom-report
    spec:
      containers:
      - image: credibleforce/lacework-custom-report:latest
        name: lacework-custom-report
        args: ["--config", "/app/reports/laceworkcli/laceworkcli_gcp_compliance_html_report.json"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1450Mi
        env:
        - name: GCP_PROJECT
          value: "kubernetes-cluster-331006"
        - name: GCP_ORG
          value:  "286188307222"
        - name: LW_ACCOUNT
          value: "lacework"
        - name: LW_API_KEY
          valueFrom:
            secretKeyRef:
              name: lacework-api
              key: api-key
        - name: LW_API_SECRET
          valueFrom:
            secretKeyRef:
              name: lacework-api
              key: api-secret